# Render Blueprint for Fukumado (ふくまど)
# すべてのサービスを一括デプロイ

services:
  # ===================================
  # Redis - キャッシュ・セッション管理
  # ===================================
  - type: redis
    name: fukumado-redis
    ipAllowList: [] # 全サービスからアクセス可能
    plan: starter # 無料プラン (25MB)
    maxmemoryPolicy: allkeys-lru

  # ===================================
  # メインバックエンドAPI
  # ===================================
  - type: web
    name: fukumado-server
    runtime: node
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm start
    customDomains:
      - domain: api.fukumado.jp
    envVars:
      - key: PORT
        value: 4000
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true # 自動生成
      - key: REDIS_URL
        fromDatabase:
          name: fukumado-redis
          property: connectionString
      - key: YOUTUBE_API_KEY
        sync: false # Renderダッシュボードで手動設定
      - key: YOUTUBE_CLIENT_ID
        sync: false
      - key: YOUTUBE_CLIENT_SECRET
        sync: false
      - key: YOUTUBE_REDIRECT_URI
        value: https://api.fukumado.jp/auth/google/callback
      - key: TWITCH_CLIENT_ID
        sync: false
      - key: TWITCH_CLIENT_SECRET
        sync: false
      - key: TWITCH_REDIRECT_URI
        value: https://api.fukumado.jp/auth/twitch/callback
    healthCheckPath: /health

  # ===================================
  # 管理ダッシュボードバックエンドAPI
  # ===================================
  - type: web
    name: fukumado-admin-server
    runtime: node
    rootDir: admin-server
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    customDomains:
      - domain: admin-api.fukumado.jp
    envVars:
      - key: PORT
        value: 4001
      - key: NODE_ENV
        value: production
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        sync: false # Renderダッシュボードで手動設定（強力なパスワード）
      - key: REDIS_URL
        fromDatabase:
          name: fukumado-redis
          property: connectionString
      - key: MAIN_BACKEND_URL
        fromService:
          type: web
          name: fukumado-server
          property: host

  # ===================================
  # クライアントフロントエンド（静的サイト）
  # ===================================
  - type: web
    name: fukumado-web
    runtime: static
    rootDir: web
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    customDomains:
      - domain: fukumado.jp
      - domain: www.fukumado.jp
    envVars:
      # Vite環境変数（ビルド時に使用）
      - key: VITE_API_URL
        fromService:
          type: web
          name: fukumado-server
          property: host

  # ===================================
  # 管理ダッシュボードフロントエンド（静的サイト）
  # ===================================
  - type: web
    name: fukumado-admin-web
    runtime: static
    rootDir: admin-web
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    customDomains:
      - domain: admin.fukumado.jp
    envVars:
      # Vite環境変数（ビルド時に使用）
      - key: VITE_ADMIN_API_URL
        fromService:
          type: web
          name: fukumado-admin-server
          property: host
      - key: VITE_ADMIN_WS_URL
        value: wss://admin-api.fukumado.jp
